select d.DBID,d.NAME,a.SNAP_ID,
       a.DBID,
       a.INSTANCE_NUMBER,
       a.STAT_ID,
       a.STAT_NAME,
       a.VALUE
  from DBA_HIST_SYSSTAT a,v$database d
 where a.STAT_NAME in ('DB time',
                       'parse count (total)',
                       'parse count (hard)',
                       'parse count (failures)',
                       'parse count (describe)',
                       'parse time cpu',
                       'parse time elapsed',
                       'physical read bytes',
                       'physical reads',
                       'physical reads cache',
                       'physical reads direct',
                       'physical reads direct (lob)',
                       'physical reads direct temporary tablespace',
                       'sorts (disk)',
                       'sorts (memory)',
                       'sorts (rows)',
                       'user calls',
                       'user commits',
                       'user rollbacks',
                       'user logons cumulative',
                       'user logouts cumulative');

