select d.DBID,d.NAME,b.SNAP_ID,
       b.DBID,
       b.INSTANCE_NUMBER,
       b.METRIC_ID,
       b.METRIC_NAME,
       b.AVERAGE,
       to_char(b.BEGIN_TIME, 'yyyy-mm-dd hh24:mi:ss') BEGIN_TIME,
       to_char(b.END_TIME, 'yyyy-mm-dd hh24:mi:ss') END_TIME
  from dba_hist_sysmetric_summary b,v$database d
 where b.METRIC_NAME in ('Host CPU Utilization (%)',
                         'Logical Reads Per Sec',
                         'Logons Per Sec',
                         'Disk Sort Per Sec',
                         'Executions Per Sec',
                         'Hard Parse Count Per Sec',
                         'Physical Read Bytes Per Sec',
                         'Physical Reads Per Sec',
                         'Physical Write Bytes Per Sec',
                         'Physical Writes Per Sec',
                         'Process Limit %',
                         'Redo Writes Per Sec',
                         'Row Cache Hit Ratio',
                         'Row Cache Miss Ratio',
                         'Session Limit %',
                         'Temp Space Used',
                         'Total Parse Count Per Sec',
                         'User Calls Per Sec',
                         'User Commits Per Sec',
                         'User Rollbacks Per Sec');

